AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  EnabledByDefault: true
  ExtraDetails: true
  TargetRubyVersion: 2.3

Metrics/LineLength:
  Max: 100

Style/Copyright:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  IgnoredMethods:
    - require
    - to
    - describe

Style/MissingElse:
  Enabled: false
